import Navtop from '@/components/modules/navtop/Navtop'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MobileNavbar from '@/components/modules/navbar/MobileNavbar'
import Navbar from '@/components/modules/navbar/Navbar'
import Footer from '@/components/modules/footer/Footer'
import MobileFooter from "@/components/modules/footer/MobileFooter"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Yolo Pay',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-[#0D0D0D]">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
        />
      </head>
      <body className={`${inter.className} font-poppins overflow-x-hidden`}>
        {/* <Navtop /> */}
        <div className="block lg:hidden">
          <MobileNavbar />
        </div>
        <div className="lg:block hidden">
          <Navbar />
        </div>
        {children}

        <div className="block lg:hidden">
          <MobileFooter />
        </div>
        <div className="lg:block hidden">
          <Footer />
        </div>
      </body>
    </html>
  );
}
